import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'rw';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.categories': 'Categories',
    'nav.cart': 'Cart',
    'nav.wishlist': 'Wishlist',
    'nav.orders': 'My Orders',
    'nav.admin': 'Admin',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.logout': 'Logout',
    'nav.search': 'Search products...',
    'nav.account': 'Account',
    // Hero
    'hero.badge': '🔥 Free Delivery on Orders Over 50,000 RWF',
    'hero.title': 'Build Better with Quality Materials',
    'hero.subtitle': 'Your one-stop shop for premium construction materials, tools, and safety equipment delivered to your doorstep.',
    'hero.cta': 'Shop Now',
    'hero.secondary': 'View Categories',
    'hero.point1': 'Certified & authentic construction materials',
    'hero.point2': 'Same-day delivery across Kigali',
    'hero.point3': 'Best prices guaranteed — or we match it',
    'hero.trust': '✦ Trusted by 2,500+ builders & contractors in Rwanda',
    'hero.stats': 'Happy Customers',
    // Categories
    'cat.title': 'Shop by Category',
    'cat.cement': 'Cement',
    'cat.tools': 'Tools',
    'cat.safety': 'Safety Equipment',
    'cat.electrical': 'Electrical',
    'cat.plumbing': 'Plumbing',
    'cat.bbq': 'BBQ',
    'cat.clothing': 'Clothing',
    // Products
    'products.title': 'Featured Products',
    'products.all': 'All Products',
    'products.addToCart': 'Add to Cart',
    'products.addedToCart': 'Added!',
    'products.viewDetails': 'View Details',
    'products.price': 'Price',
    'products.inStock': 'In Stock',
    'products.outOfStock': 'Out of Stock',
    'products.discount': 'OFF',
    // Cart
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.total': 'Total',
    'cart.subtotal': 'Subtotal',
    'cart.delivery': 'Delivery Fee',
    'cart.checkout': 'Proceed to Checkout',
    'cart.remove': 'Remove',
    'cart.quantity': 'Qty',
    // Checkout
    'checkout.title': 'Checkout',
    'checkout.delivery': 'Delivery',
    'checkout.pickup': 'Pickup',
    'checkout.address': 'Delivery Address',
    'checkout.phone': 'Phone Number',
    'checkout.name': 'Full Name',
    'checkout.city': 'City',
    'checkout.payment': 'Payment Method',
    'checkout.mobileMoney': 'Mobile Money',
    'checkout.card': 'Card Payment',
    'checkout.placeOrder': 'Place Order',
    'checkout.orderPlaced': 'Order placed successfully!',
    // Orders
    'orders.title': 'My Orders',
    'orders.pending': 'Pending',
    'orders.delivering': 'Delivering',
    'orders.completed': 'Completed',
    'orders.empty': 'No orders yet',
    'orders.orderNumber': 'Order #',
    'orders.date': 'Date',
    'orders.status': 'Status',
    'orders.items': 'items',
    // Wishlist
    'wishlist.title': 'My Wishlist',
    'wishlist.empty': 'Your wishlist is empty',
    'wishlist.add': 'Add to Wishlist',
    'wishlist.remove': 'Remove from Wishlist',
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Create Account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.name': 'Full Name',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.welcome': 'Welcome back',
    'auth.createAccount': 'Create your account',
    // Admin
    'admin.dashboard': 'Dashboard',
    'admin.products': 'Products',
    'admin.orders': 'Orders',
    'admin.inventory': 'Inventory',
    'admin.analytics': 'Analytics',
    'admin.totalSales': 'Total Sales',
    'admin.totalOrders': 'Total Orders',
    'admin.totalProducts': 'Total Products',
    'admin.totalCustomers': 'Total Customers',
    'admin.addProduct': 'Add Product',
    'admin.editProduct': 'Edit Product',
    'admin.deleteProduct': 'Delete Product',
    // Footer
    'footer.about': 'About Us',
    'footer.aboutText': 'SANOBUY.rw is your trusted marketplace for quality construction materials in Rwanda.',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact Us',
    'footer.rights': '© 2026 SANOBUY.rw. All rights reserved.',
    'footer.email': 'info@sanobuy.rw',
    'footer.phone': '+250 788 000 000',
    // Notifications
    'notif.title': 'Notifications',
    'notif.empty': 'No new notifications',
    // General
    'general.currency': 'RWF',
    'general.viewAll': 'View All',
    'general.back': 'Back',
    'general.save': 'Save',
    'general.cancel': 'Cancel',
    'general.delete': 'Delete',
    'general.edit': 'Edit',
    'general.loading': 'Loading...',
  },
  rw: {
    'nav.home': 'Ahabanza',
    'nav.products': 'Ibicuruzwa',
    'nav.categories': 'Ibyiciro',
    'nav.cart': 'Agakari',
    'nav.wishlist': 'Ibyifuzo',
    'nav.orders': 'Ibyo Naguze',
    'nav.admin': 'Ubuyobozi',
    'nav.login': 'Injira',
    'nav.register': 'Iyandikishe',
    'nav.logout': 'Sohoka',
    'nav.search': 'Shakisha ibicuruzwa...',
    'nav.account': 'Konti',
    'hero.badge': '🔥 Ubutumwa Kubuntu ku Masoko arenze 50,000 RWF',
    'hero.title': 'Kubaka Neza Ukoresheje Ibikoresho Byiza',
    'hero.subtitle': 'Isoko ryawe ryose ry\'ibikoresho byo kubaka, ibikoresho, n\'ibikoresho byo kurinda bigezwa ku muryango wawe.',
    'hero.cta': 'Gura Nonaha',
    'hero.secondary': 'Reba Ibyiciro',
    'hero.point1': 'Ibikoresho byo kubaka byemewe kandi nyabyo',
    'hero.point2': 'Ubutumwa bw\'umunsi umwe muri Kigali yose',
    'hero.point3': 'Ibiciro byiza — cyangwa turahura',
    'hero.trust': '✦ Kwizerwaho n\'ababaka 2,500+ mu Rwanda',
    'hero.stats': 'Abakiriya Bishimye',
    'cat.title': 'Gura Ukurikije Icyiciro',
    'cat.cement': 'Sima',
    'cat.tools': 'Ibikoresho',
    'cat.safety': 'Ibyo Kurinda',
    'cat.electrical': 'Amashanyarazi',
    'cat.plumbing': 'Amazi',
    'cat.bbq': 'BBQ',
    'cat.clothing': 'Imyambaro',
    'products.title': 'Ibicuruzwa Byihariye',
    'products.all': 'Ibicuruzwa Byose',
    'products.addToCart': 'Shyira mu Gakari',
    'products.addedToCart': 'Byashyizwemo!',
    'products.viewDetails': 'Reba Birambuye',
    'products.price': 'Igiciro',
    'products.inStock': 'Birahari',
    'products.outOfStock': 'Ntibiboneka',
    'products.discount': 'KUGABANYA',
    'cart.title': 'Agakari k\'Ibicuruzwa',
    'cart.empty': 'Agakari kawe ni ubusa',
    'cart.total': 'Igiteranyo',
    'cart.subtotal': 'Igiciro cy\'Ibicuruzwa',
    'cart.delivery': 'Amafaranga yo Kugeza',
    'cart.checkout': 'Komeza Kwishyura',
    'cart.remove': 'Kuraho',
    'cart.quantity': 'Umubare',
    'checkout.title': 'Kwishyura',
    'checkout.delivery': 'Kugeza',
    'checkout.pickup': 'Gufata',
    'checkout.address': 'Aderesi yo Kugezaho',
    'checkout.phone': 'Nomero ya Telefoni',
    'checkout.name': 'Amazina Yose',
    'checkout.city': 'Umujyi',
    'checkout.payment': 'Uburyo bwo Kwishyura',
    'checkout.mobileMoney': 'Mobile Money',
    'checkout.card': 'Ikarita',
    'checkout.placeOrder': 'Gusaba',
    'checkout.orderPlaced': 'Ibyo wasabye byakiriwe neza!',
    'orders.title': 'Ibyo Naguze',
    'orders.pending': 'Bitegereje',
    'orders.delivering': 'Birimo Koherezwa',
    'orders.completed': 'Byarangiye',
    'orders.empty': 'Nta byo waguze',
    'orders.orderNumber': 'Nomero #',
    'orders.date': 'Itariki',
    'orders.status': 'Uko Bihagaze',
    'orders.items': 'ibicuruzwa',
    'wishlist.title': 'Ibyifuzo Byange',
    'wishlist.empty': 'Nta byifuzo ufite',
    'wishlist.add': 'Ongeraho mu Byifuzo',
    'wishlist.remove': 'Kuraho mu Byifuzo',
    'auth.login': 'Injira',
    'auth.register': 'Fungura Konti',
    'auth.email': 'Imeyili',
    'auth.password': 'Ijambo ry\'Ibanga',
    'auth.confirmPassword': 'Emeza Ijambo ry\'Ibanga',
    'auth.name': 'Amazina Yose',
    'auth.noAccount': 'Ntufite konti?',
    'auth.hasAccount': 'Usanzwe ufite konti?',
    'auth.welcome': 'Murakaza neza',
    'auth.createAccount': 'Fungura konti yawe',
    'admin.dashboard': 'Ikibaho',
    'admin.products': 'Ibicuruzwa',
    'admin.orders': 'Ibyo Basabye',
    'admin.inventory': 'Ububiko',
    'admin.analytics': 'Isesengura',
    'admin.totalSales': 'Igurisha Ryose',
    'admin.totalOrders': 'Ibisabwa Byose',
    'admin.totalProducts': 'Ibicuruzwa Byose',
    'admin.totalCustomers': 'Abakiriya Bose',
    'admin.addProduct': 'Ongeraho Igicuruzwa',
    'admin.editProduct': 'Hindura Igicuruzwa',
    'admin.deleteProduct': 'Siba Igicuruzwa',
    'footer.about': 'Abo Turibo',
    'footer.aboutText': 'SANOBUY.rw ni isoko ryawe ry\'ibikoresho byo kubaka mu Rwanda.',
    'footer.quickLinks': 'Aho Ugera Vuba',
    'footer.contact': 'Twandikire',
    'footer.rights': '© 2026 SANOBUY.rw. Uburenganzira bwose bwabitswe.',
    'footer.email': 'info@sanobuy.rw',
    'footer.phone': '+250 788 000 000',
    'notif.title': 'Amakuru',
    'notif.empty': 'Nta makuru mashya',
    'general.currency': 'RWF',
    'general.viewAll': 'Reba Byose',
    'general.back': 'Subira Inyuma',
    'general.save': 'Bika',
    'general.cancel': 'Hagarika',
    'general.delete': 'Siba',
    'general.edit': 'Hindura',
    'general.loading': 'Gutegereza...',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>('en');
  const t = (key: string) => translations[lang][key] || key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be inside LanguageProvider');
  return ctx;
};
